### ISSUE TITLE
Ajouter la documentation de la "prise en main" dans le README directement

### ISSUE THREAD

**Issue by bzg** [codegouvfr/eleventy-dsfr#11]
Pour accélérer la prise en main, la mettre dans le README directement.

Ensuite, le README peut proposer de continuer de lire la documentation dans GitHub pour chaque composant.

**Comment by hjonin** [comment]
L'article de Prise en main a été rapatrié comme une section du README, le lien vers le reste de la doc a été mis à jour.

**Comment by bzg** [comment]
> L'article de Prise en main a été rapatrié comme une section du README, le lien vers le reste de la doc a été mis à jour.

Top, merci !
