### ISSUE TITLE
Clignotement en mode sombre

### ISSUE THREAD

**Issue by slafayIGN** [codegouvfr/eleventy-dsfr#13]
Au chargement des pages en mode sombre, un effet de clignotement se produit avec d'abord la page en mode clair puis très rapidement un passage en mode sombre.
Ceci se produit lors de tous les changements de pages.

Je ne sais pas ce qui, dans le fonctionnement d'11ty, justifie cet effet.

**Comment by hjonin** [comment]
Merci d'avoir soulevé ce problème !

Cela est dû au mode de fonctionnement des thèmes du DSFR. Le fix proposé par https://github.com/demarches-simplifiees/demarches-simplifiees.fr/pull/9727 a permis de le contourner.
