### ISSUE TITLE
Date des articles de documentation

### ISSUE THREAD

**Issue by slafayIGN** [codegouvfr/eleventy-dsfr#15]
Sur le déploiement du site de démo sur github pages, les articles de la documentation ont tous la même date malgré leur configuration à `git Last Modified`.

C'est parce que le build a lieu sur un dépôt dont le checkout a été fait sans aucun historique, seulement le dernier commit.

Pour que les dates soient correctes dans le déploiement, il faut modifier l'action checkout du workflow pour qu'elle prenne tout l'historique

```diff
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
       - name: Setup Pages
         uses: actions/configure-pages@v4
       - name: Build with Eleventy
```

**Comment by hjonin** [comment]
Merci beaucoup pour cette correction (et cette information) ! Cela a été pris en compte dans le commit https://github.com/codegouvfr/eleventy-dsfr/commit/995daed5598dfe4218d7dd39b55a031e150b5d8e.
