### ISSUE TITLE
Possibilité d'accéder à des exemples de sites déployés utilisant eleventy-dsfr ?

### ISSUE THREAD

**Issue by teotimepacreau** [codegouvfr/eleventy-dsfr#16]
Bonjour,
Je travaille pour l'Etat de Pays de la Loire et nous étudions la possibilité de réaliser l'intégration d'une maquette via Eleventy-dsfr,

J'aimerais savoir si ils existent déjà des sites déployés utilisant eleventy-dsfr s'il vous plaît ?

Excusez moi de passer par ce canal, mais j'aimerais pouvoir vous contacter à ce sujet s'il vous plaît @hjonin

**Comment by hjonin** [comment]
Bonjour,

Le site de la mission https://code.gouv.fr/fr/ (https://github.com/codegouvfr/codegouvfr-website) utilise eleventy-dsfr (également documenté dans la partiedu README https://github.com/codegouvfr/eleventy-dsfr?tab=readme-ov-file#d%C3%A9monstration-et-r%C3%A9utilisations).

Le site de la mission Numérique écoresponsable https://ecoresponsable.numerique.gouv.fr/ (https://github.com/DISIC/MiNumEco) utilise eleventy, mais n'utilise pas encore le template eleventy-dsfr car il a été créé antérieurement.

CC @bzg

**Comment by bzg** [comment]
Pour toutes les questions juridiques sur l'autorisation à utiliser le DSFR, vous pouvez contacter directement le SIG -  https://www.systeme-de-design.gouv.fr/a-propos/conditions-generales-d-utilisation/

**Comment by hjonin** [comment]
Pour discuter d'eleventy-dsfr en particulier, vous pouvez me contacter sur contact@code.gouv.fr où je pourrai prendre le relai.
